name: Test the workflows against UseGalaxy BE
on: push
  # switch to this once the CI action is working fine
  #schedule:
    # Run every day at midnight 
    #- cron: '00 00 * * *'
jobs:
  if: github.ref == 'refs/heads/master'
  run_planemo_test:
    name: Checkout repo   
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - uses: actions/setup-python@v2

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt  # this is optional

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
    - run: | 
           #python -m venv ./.venv && . ./.venv/bin/activate && 
           pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      #if: steps.cache-venv.outputs.cache-hit != 'true'

    #- uses: actions/cache@v2
      #id: cache-venv  # name for referring later
      #with:
        #path: ./.venv/  # what we cache: the virtualenv
        # The cache key depends on requirements.txt
        #key: venv-planemo
          #restore-keys: |
          #${{ runner.os }}-venv-
    # Build a virtualenv, but only if it doesn't already exist
    # Run tests
    # Note that you have to activate the virtualenv in every step
    # because GitHub actions doesn't preserve the environment
    #- run: . ./.venv/bin/activate && nosetests tests/
    #- name: Cache venv
      #uses: actions/cache@v2
      #with:
        #path: |
          #./.venv
    - name: Run planemo tests
      run: |
        # this runs the tests using planemo, parses the results and saves it ready to be pushed as a post in test_reults.md
        sh run_workflow_tests.sh ${{ secrets.GALAXY_BE_KEY }}
        cat test_results.md
    - name: Save test_results.txt to use in next job
      uses: actions/upload-artifact@master
      with:
        name: test_results.md
        path: ./test_results.md
  commit_test_results:
    if: github.ref == 'refs/heads/master'
    needs: run_planemo_test 
    name: Commit changes to gh-pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
      ## need to define the branch   gh-pages
    - uses: actions/download-artifact@master
      with:
        name: test_results.md
        path: test_results.md
    - run: | 
        post_name=$(date '+%Y-%m-%d').md
        mv test_results.md _posts/$(post_name)
    - uses: peter-evans/create-pull-request@v3.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update workflow tests"
        title: "Weekly workflow tests on UseGalaxy.be"
        body: "Automated tests"
        labels: Automation
        branch: gh-pages
        #base: master
